// <auto-generated />
using SistemaCondominios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EjemploClase6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724011452_CrearUsuario")]
    partial class CrearUsuario
    {
        /// <inheritdoc />
        
    }
}
