// <auto-generated />
using SistemaCondominios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EjemploClase6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250627191131_InitialCreate")]
    partial class InitialCreate
    {
        
    }
}
